export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
// posko
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "GET_PETUGAS";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
// pengungsi
export const GET_PENGUNGSI = "GET_PENGUNGSI";
export const CLEAR_PENGUNGSI = "CLEAR_PENGUNGSI";
export const PENGUNGSI_ERROR = "PENGUNGSI_ERROR";
export const UPDATE_PENGUNGSI = "UPDATE_PENGUNGSI";
// bantuan masuk
export const GET_BANTUAN_MASUK = "GET_BANTUAN_MASUK";
export const CLEAR_BANTUAN_MASUK = "CLEAR_BANTUAN_MASUK";
export const BANTUAN_MASUK_ERROR = "BANTUAN_MASUK_ERROR";
export const UPDATE_BANTUAN_MASUK = "UPDATE_BANTUAN_MASUK";
// fasilitas posko
export const GET_FASILITAS_POSKO = "GET_FASILITAS_POSKO";
export const FASILITAS_POSKO_ERROR = "FASILITAS_POSKO_ERROR";
export const UPDATE_FASILITAS_POSKO = "UPDATE_FASILITAS_POSKO";
export const CLEAR_FASILITAS_POSKO = "CLEAR_FASILITAS_POSKO";

export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
