export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "GET_PETUGAS";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
// posko
export const GET_PENGUNGSI = "GET_PENGUNGSI";
export const CLEAR_PENGUNGSI = "CLEAR_PENGUNGSI";
export const PENGUNGSI_ERROR = "PENGUNGSI_ERROR";
export const UPDATE_PENGUNGSI = "UPDATE_PENGUNGSI";
// bantuan masuk
export const GET_BANTUAN_MASUK = "GET_BANTUAN_MASUK";
export const CLEAR_BANTUAN_MASUK = "CLEAR_BANTUAN_MASUK";
export const BANTUAN_MASUK_ERROR = "BANTUAN_MASUK_ERROR";
export const UPDATE_BANTUAN_MASUK = "UPDATE_BANTUAN_MASUK";
// fasilitas posko
export const GET_FASILITAS_POSKO = "GET_FASILITAS_POSKO";
export const FASILITAS_POSKO_ERROR = "FASILITAS_POSKO_ERROR";
export const UPDATE_FASILITAS_POSKO = "UPDATE_FASILITAS_POSKO";
export const CLEAR_FASILITAS_POSKO = "CLEAR_FASILITAS_POSKO";
// permintaan bantuan
export const GET_PERMINTAAN_BANTUAN = "GET_PERMINTAAN_BANTUAN";
export const UPDATE_PERMINTAAN_BANTUAN = "UPDATE_PERMINTAAN_BANTUAN";
export const PERMINTAAN_BANTUAN_ERROR = "PERMINTAAN_BANTUAN_ERROR";
export const CLEAR_PERMINTAAN_BANTUAN = "CLEAR_PERMINTAAN_BANTUAN";

export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

// petugas
export const GET_PROFILE_PETUGAS = "GET_PROFILE_PETUGAS";
export const UPDATE_PROFILE_PETUGAS = "UPDATE_PROFILE_PETUGAS";
export const CLEAR_PROFILE_PETUGAS = "CLEAR_PROFILE_PETUGAS";
export const PROFILE_PETUGAS_ERROR = "PROFILE_PETUGAS_ERROR";

export const GET_LAPORAN_BENCANA = "GET_LAPORAN_BENCANA";
export const UPDATE_LAPORAN_BENCANA = "UPDATE_LAPORAN_BENCANA";
export const CLEAR_LAPORAN_BENCANA = "CLEAR_LAPORAN_BENCANA";
export const LAPORAN_BENCANA_ERROR = "LAPORAN_BENCANA_ERROR";

export const GET_LAPORAN_HARIAN = "GET_LAPORAN_HARIAN";
export const UPDATE_LAPORAN_HARIAN = "UPDATE_LAPORAN_HARIAN";
export const CLEAR_LAPORAN_HARIAN = "CLEAR_LAPORAN_HARIAN";
export const LAPORAN_HARIAN_ERROR = "LAPORAN_HARIAN_ERROR";

// admin
export const GET_PROFILE_ADMIN = "GET_PROFILE_ADMIN";
export const UPDATE_PROFILE_ADMIN = "UPDATE_PROFILE_ADMIN";
export const CLEAR_PROFILE_ADMIN = "CLEAR_PROFILE_ADMIN";
export const PROFILE_ADMIN_ERROR = "PROFILE_ADMIN_ERROR";

export const GET_BANTUAN_UTAMA = "GET_BANTUAN_UTAMA";
export const UPDATE_BANTUAN_UTAMA = "UPDATE_BANTUAN_UTAMA";
export const CLEAR_BANTUAN_UTAMA = "CLEAR_BANTUAN_UTAMA";
export const BANTUAN_UTAMA_ERROR = "BANTUAN_UTAMA_ERROR";
